### ISSUE TITLE
Print order of object fields

### ISSUE THREAD

**Issue by vlasakm** [kondziu/FMLtest#3]
Please consider modifying the test case `object.bc` so that it doesn't depend on the fact that object fields are printed in insertion order.

Other test cases pass when fields are printed in lexicographic order, only `object.bc` doesn't.

```diff
5c5
< object(..=object(), x=3, z=2, y=4)
---
> object(..=object(), x=3, y=4, z=2)
```

I know that it is probably preferable to keep the order of the fields like it is in the source file, but given that in the bytecode fields are already reversed, it seems kind of arbitrary.

Lexicographic sorting is likewise deterministic and if the test cases are compatible with both orderings, everyone should be satisfied. (At least until we start interning the strings and then the easiest order would be the order in which field names appear in the constants array...).

**Comment by kondziu** [comment]
Lexographical order for printing is not a bad idea. Let's do that.

**Comment by vlasakm** [comment]
Well I suggested only changing the test case, since I don't want to break everybody else's implementations.

Though I agree that the AST spec doesn't define any print order, and lexicographic would be preferable considering hash map implementations.

**Comment by kondziu** [comment]
It's done now.
